export const difficlty = ["easy", "medium", "hard"];
export const category = ["breakfast", "lunch", "dinner", "dessert"];
export const ingredients = [
  "flour",
  "butter",
  "sugar",
  "chocolate chips",
  "milk",
  "eggs",
  "baking powder",
  "chicken breast",
  "lettuce",
  "tomatoes",
  "olive oil",
  "lemon",
  "spaghetti",
  "parmesan",
  "bacon",
  "black pepper",
  "broccoli",
  "carrots",
  "bell peppers",
  "soy sauce",
  "garlic",
  "bread",
  "cinnamon",
  "ground beef",
  "tortillas",
  "cheese",
  "lentils",
  "onion",
  "vegetable broth",
  "cocoa powder",
  "salt",
];
