import { workType } from './models/job.enum';
import { Job } from './models/job.model';

export const mockJobs: Job[] = [
  {
    id: 1,
    companyName: 'Google',
    companyLogo: 'assets/logos/google.png',
    expires: '2025-12-31',
    position: 'Frontend Developer',
    startingSalary: 5000,
    workType: workType.REMOTE,
    location: 'Mountain View',
    country: 'USA',
    qualifications: [
      'Bachelor’s degree in Computer Science or related field',
      '3+ years of hands-on experience with Angular or React',
      'Strong understanding of web fundamentals (HTML5, CSS3, JavaScript/TypeScript)',
      'Experience with version control systems such as Git and GitHub',
      'Familiarity with Agile methodologies and CI/CD pipelines',
    ],
    description: `As a Frontend Developer at Google, you will be responsible for 
    designing and building scalable, high-performance web applications. 
    You will work closely with UX designers and backend engineers to deliver 
    seamless user experiences. The role involves writing clean, testable code, 
    optimizing application performance, and ensuring accessibility and cross-browser compatibility.`,
    isApplied: false,
    companyAddress: '1600 Amphitheatre Parkway, CA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.google.com',
    techStack: [
      'Angular for large-scale single-page applications',
      'TypeScript for type-safe development',
      'RxJS for reactive programming and async data streams',
      'HTML5 and CSS3 for building responsive layouts',
      'Jest/Cypress for unit and end-to-end testing',
    ],
    prefferedSkills: [
      'Excellent problem-solving and debugging skills',
      'Strong communication and ability to collaborate in cross-functional teams',
      'Attention to detail in UI/UX implementation',
      'Ability to write reusable and maintainable code',
      'Passion for staying up-to-date with emerging frontend technologies',
    ],
    companyEmployees: 32,
    companyFollowers: 1232,
    companyDescription: [
      'Google is a global technology powerhouse known for its mission to organize the world’s information and make it universally accessible and useful. The company has reshaped how billions of people learn, communicate, and work in the modern world.',
      'Beyond its search engine, Google has created a massive ecosystem with Android, YouTube, Google Cloud, and AI-driven tools that empower both businesses and individuals. These innovations touch almost every aspect of digital life today.',
      'With a culture of continuous innovation, data-driven decision making, and user-focused design, Google invests heavily in cutting-edge technologies like quantum computing, sustainability initiatives, and next-generation AI research.',
    ],
    createdAt: '2025-09-14T14:15:00',
  },
  {
    id: 2,
    companyName: 'Apple',
    companyLogo: 'assets/logos/apple.png',
    expires: '2025-11-15',
    position: 'Backend Developer',
    startingSalary: 6000,
    workType: workType.ONSITE,
    location: 'Cupertino',
    country: 'USA',
    qualifications: [
      'Bachelor’s degree in Computer Science or related field',
      '3+ years experience in Node.js or Java backend development',
      'Proficient in RESTful API design and development',
      'Familiarity with database systems such as MySQL, PostgreSQL, or MongoDB',
      'Understanding of cloud infrastructure and deployment practices',
    ],
    description: `Work on scalable and high-performance backend services. 
    Design and implement APIs, integrate with front-end applications, 
    and ensure security, reliability, and performance of backend systems. 
    Collaborate with cross-functional teams to define technical requirements.`,
    isApplied: true,
    companyAddress: '1 Apple Park Way, CA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.apple.com',
    techStack: [
      'Node.js and Express for backend services',
      'Java and Spring Boot for enterprise applications',
      'SQL and NoSQL databases for data storage',
      'Redis or Memcached for caching solutions',
      'Docker/Kubernetes for containerization and orchestration',
    ],
    prefferedSkills: [
      'Strong analytical and problem-solving skills',
      'Performance optimization and debugging',
      'API design and integration experience',
      'Collaboration in agile teams',
      'Experience with CI/CD pipelines and automation',
    ],
    companyEmployees: 21094,
    companyFollowers: 2109423,
    companyDescription: [
      'Apple is a world-renowned innovator in consumer electronics, software, and digital services. Its iconic products, including the iPhone, iPad, and Mac, have transformed industries and set new standards in design and performance.',
      'The company blends cutting-edge technology with sleek, minimalist design, creating ecosystems where hardware, software, and services work together seamlessly. Apple also places strong emphasis on privacy, sustainability, and user experience.',
      'Apple’s culture thrives on excellence, innovation, and pushing boundaries. With initiatives in health, wearable devices, and augmented reality, Apple continues to redefine the future of personal technology and digital ecosystems.',
    ],
    createdAt: '2025-09-15T09:30:00',
  },
  {
    id: 3,
    companyName: 'Amazon',
    companyLogo: 'assets/logos/amazon.png',
    expires: '2025-10-01',
    position: 'Data Scientist',
    startingSalary: 5500,
    workType: workType.HYBRID,
    location: 'Seattle',
    country: 'USA',
    qualifications: [
      'Master’s degree in Data Science, Statistics, or related field',
      'Proficiency in Python, R, or similar programming languages',
      'Experience with machine learning algorithms and frameworks',
      'Ability to analyze and interpret large datasets',
      'Knowledge of cloud platforms such as AWS or GCP',
    ],
    description: `Analyze large datasets to generate insights and predictions. 
    Build machine learning models, work closely with product and engineering teams, 
    and implement scalable data pipelines. Present findings to stakeholders and provide recommendations.`,
    isApplied: false,
    companyAddress: '410 Terry Ave N, WA',
    companyIndustry: 'E-commerce',
    companyWebsite: 'https://www.amazon.com',
    techStack: [
      'Python and R for statistical analysis',
      'TensorFlow and PyTorch for machine learning',
      'Pandas, NumPy for data processing',
      'AWS or GCP for cloud computing',
      'SQL and NoSQL databases for data storage',
    ],
    prefferedSkills: [
      'Data visualization and storytelling',
      'Statistical modeling and hypothesis testing',
      'Critical thinking and problem-solving',
      'Communication with cross-functional teams',
      'Experience with big data tools like Spark or Hadoop',
    ],
    companyEmployees: 523,
    companyFollowers: 2312,
    companyDescription: [
      'Amazon is a multinational giant that transformed online retail and cloud computing, becoming one of the most influential companies worldwide. Known for its relentless focus on customer obsession, Amazon constantly seeks to improve speed, convenience, and value.',
      'The company’s impact extends far beyond e-commerce, with innovations in AWS, Alexa, Kindle, and logistics. AWS in particular powers millions of businesses globally, driving advancements in cloud technologies and scalable infrastructure.',
      'Amazon is also investing heavily in areas like artificial intelligence, robotics, healthcare, and entertainment, aiming to shape the future of digital services and create a more sustainable and connected global economy.',
    ],
    createdAt: '2025-09-13T20:45:00',
  },
  {
    id: 4,
    companyName: 'Netflix',
    companyLogo: 'assets/logos/netflix.png',
    expires: '2025-09-20',
    position: 'UX Designer',
    startingSalary: 4800,
    workType: workType.HYBRID,
    location: 'Los Gatos',
    country: 'USA',
    qualifications: [
      'Portfolio showcasing UX design projects',
      'Proficiency in Figma, Adobe XD, or Sketch',
      'Experience in wireframing, prototyping, and user testing',
      'Understanding of user-centered design principles',
      'Strong visual design and interaction skills',
    ],
    description: `Design intuitive and user-friendly interfaces for streaming platforms. 
    Conduct user research, create wireframes and prototypes, 
    and collaborate closely with product managers and developers to ensure seamless user experiences.`,
    isApplied: true,
    companyAddress: '100 Winchester Cir, CA',
    companyIndustry: 'Entertainment',
    companyWebsite: 'https://www.netflix.com',
    techStack: [
      'Figma, Adobe XD, Sketch for design',
      'InVision for prototyping',
      'HTML/CSS basics for design handoff',
      'User testing and feedback tools',
      'Design systems and component libraries',
    ],
    prefferedSkills: [
      'Creativity and innovation in design',
      'User research and usability testing',
      'Wireframing and prototyping',
      'Collaboration with development teams',
      'Attention to detail and design consistency',
    ],
    companyEmployees: 121,
    companyFollowers: 12314,
    companyDescription: [
      'Netflix is the world’s leading streaming entertainment service, offering movies, series, and documentaries to millions of subscribers globally.',
      'Leveraging data-driven insights, Netflix creates personalized experiences while investing heavily in original productions.',
      'The company’s culture is built on freedom, responsibility, and innovation, pushing the boundaries of how entertainment is produced, delivered, and enjoyed worldwide.',
    ],
    createdAt: '2025-09-12T08:00:00',
  },
  {
    id: 5,
    companyName: 'Microsoft',
    companyLogo: 'assets/logos/microsoft.png',
    expires: '2025-08-30',
    position: 'Cloud Engineer',
    startingSalary: 6200,
    workType: workType.ONSITE,
    location: 'Redmond',
    country: 'USA',
    qualifications: [
      'Experience with Azure and AWS cloud platforms',
      'Knowledge of containerization and orchestration (Docker, Kubernetes)',
      'Familiarity with CI/CD pipelines and DevOps practices',
      'Ability to monitor and optimize cloud systems',
      'Understanding of networking and security principles',
    ],
    description: `Manage, deploy, and optimize cloud infrastructure. 
    Implement scalable and secure cloud solutions, 
    monitor system performance, and automate deployments. 
    Collaborate with developers and other engineers to ensure high availability.`,
    isApplied: false,
    companyAddress: '1 Microsoft Way, WA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.microsoft.com',
    techStack: [
      'Azure and AWS for cloud services',
      'Kubernetes and Docker for container management',
      'Terraform for infrastructure as code',
      'Linux and Windows server administration',
      'Monitoring tools like Prometheus or Grafana',
    ],
    prefferedSkills: [
      'Automation and scripting',
      'Problem-solving and troubleshooting',
      'System monitoring and optimization',
      'Collaboration in cross-functional teams',
      'Strong understanding of security best practices',
    ],
    companyEmployees: 2141,
    companyFollowers: 203020,
    companyDescription: [
      'Microsoft is a global leader in software, cloud, and enterprise solutions, best known for Windows, Office, and Azure.',
      'With a mission to empower every person and organization to achieve more, Microsoft drives innovation across productivity tools, AI, and developer platforms.',
      'The company fosters collaboration, inclusivity, and long-term impact, shaping the digital future while supporting billions of people worldwide.',
    ],
    createdAt: '2025-09-11T18:30:00',
  },
  {
    id: 6,
    companyName: 'Facebook',
    companyLogo: 'assets/logos/facebook.png',
    expires: '2025-11-05',
    position: 'Mobile Developer',
    startingSalary: 5300,
    workType: workType.HYBRID,
    location: 'Menlo Park',
    country: 'USA',
    qualifications: [
      'Experience with iOS (Swift) and Android (Kotlin) development',
      'Proficiency in React Native for cross-platform apps',
      'Understanding of RESTful APIs and GraphQL',
      'Experience with app deployment on App Store and Google Play',
      'Knowledge of mobile performance optimization',
    ],
    description: `Develop high-quality mobile applications for social media platforms. 
    Implement features, optimize performance, and ensure a smooth user experience. 
    Collaborate with designers and backend engineers to deliver robust applications.`,
    isApplied: false,
    companyAddress: '1 Hacker Way, CA',
    companyIndustry: 'Social Media',
    companyWebsite: 'https://www.facebook.com',
    techStack: [
      'React Native for cross-platform apps',
      'Swift for iOS development',
      'Kotlin for Android development',
      'GraphQL for efficient data queries',
      'Jest/Detox for testing',
    ],
    prefferedSkills: [
      'Cross-platform development expertise',
      'Debugging and problem-solving',
      'Effective communication with team members',
      'UI/UX awareness for mobile apps',
      'Continuous learning and adaptation',
    ],
    companyEmployees: 5,
    companyFollowers: 21,
    companyDescription: [
      'Facebook, now part of Meta, is one of the largest social networking platforms in the world, connecting billions of users across diverse communities.',
      'The company invests heavily in technologies such as artificial intelligence, augmented reality, and virtual reality to redefine digital interaction and the future of communication.',
      'With a mission to bring the world closer together, Facebook empowers users to share experiences, build meaningful relationships, and explore new ways of engaging in a global digital society.',
    ],
    createdAt: '2025-09-10T12:10:00',
  },
  {
    id: 7,
    companyName: 'Tesla',
    companyLogo: 'assets/logos/tesla.png',
    expires: '2025-12-15',
    position: 'Mechanical Engineer',
    startingSalary: 5000,
    workType: workType.ONSITE,
    location: 'Palo Alto',
    country: 'USA',
    qualifications: [
      'Bachelor’s degree in Mechanical Engineering or related field',
      'Experience with CAD software such as AutoCAD or SolidWorks',
      'Knowledge of mechanical systems and materials',
      'Understanding of manufacturing processes and prototyping',
      'Problem-solving and analytical skills',
    ],
    description: `Design and develop components for electric vehicles. 
    Work on mechanical simulations, prototyping, and testing. 
    Collaborate with cross-functional teams to improve vehicle performance and safety.`,
    isApplied: true,
    companyAddress: '3500 Deer Creek Rd, CA',
    companyIndustry: 'Automotive',
    companyWebsite: 'https://www.tesla.com',
    techStack: [
      'AutoCAD and SolidWorks for CAD design',
      'MATLAB for simulations',
      'Ansys for finite element analysis',
      '3D modeling and prototyping tools',
      'Mechanical testing and measurement tools',
    ],
    prefferedSkills: [
      'Attention to detail',
      'Problem-solving and analytical thinking',
      'Teamwork and collaboration',
      'Understanding of mechanical tolerances',
      'Ability to innovate and improve designs',
    ],
    companyEmployees: 2,
    companyFollowers: 3,
    companyDescription: [
      'Tesla is a trailblazer in electric vehicles, renewable energy, and clean technology, reshaping the automotive industry with its mission to accelerate the world’s transition to sustainable energy.',
      'Beyond cars like the Model 3, Model S, and Cybertruck, Tesla develops products such as Powerwall and Solar Roof that promote energy independence.',
      'Its culture encourages bold innovation, rapid prototyping, and constant improvement, driving progress not only in transportation but also in sustainable global energy solutions.',
    ],
    createdAt: '2025-09-09T22:50:00',
  },
  {
    id: 8,
    companyName: 'Spotify',
    companyLogo: 'assets/logos/spotify.png',
    expires: '2025-10-30',
    position: 'Product Manager',
    startingSalary: 5800,
    workType: workType.REMOTE,
    location: 'Stockholm',
    country: 'Sweden',
    qualifications: [
      'Experience in agile product management',
      'Strong analytical and problem-solving skills',
      'Ability to coordinate cross-functional teams',
      'Understanding of product lifecycle and user-centered design',
      'Excellent communication and stakeholder management skills',
    ],
    description: `Lead product development initiatives, define roadmaps, and prioritize features. 
    Work closely with designers, engineers, and marketing teams to deliver successful products. 
    Monitor KPIs and ensure alignment with business goals.`,
    isApplied: false,
    companyAddress: 'Regeringsgatan 19, Stockholm',
    companyIndustry: 'Music Streaming',
    companyWebsite: 'https://www.spotify.com',
    techStack: [
      'Jira and Confluence for project management',
      'Agile frameworks like Scrum or Kanban',
      'Analytics tools for product insights',
      'Prototyping tools for feature validation',
      'Collaboration and communication platforms',
    ],
    prefferedSkills: [
      'Leadership and team coordination',
      'Strategic thinking and decision making',
      'Excellent communication skills',
      'Problem-solving mindset',
      'Adaptability and prioritization',
    ],
    companyEmployees: 213,
    companyFollowers: 225,
    companyDescription: [
      'Spotify is the world’s leading music and audio streaming platform, offering millions of tracks, podcasts, and personalized playlists to a global user base.',
      'By combining advanced data analytics with creative curation, Spotify delivers unique recommendations and empowers users to discover new artists and genres every day.',
      'The company fosters a culture of inclusivity, creativity, and innovation while reshaping the way people connect with music and audio worldwide.',
    ],
    createdAt: '2025-09-08T07:25:00',
  },
  {
    id: 9,
    companyName: 'Airbnb',
    companyLogo: 'assets/logos/airbnb.png',
    expires: '2025-09-10',
    position: 'Frontend Developer',
    startingSalary: 5100,
    workType: workType.HYBRID,
    location: 'San Francisco',
    country: 'USA',
    qualifications: [
      'Experience with React and Angular frameworks',
      'Proficient in HTML5, CSS3, and JavaScript/TypeScript',
      'Understanding of responsive and accessible design',
      'Experience with version control and collaborative workflows',
      'Familiarity with testing frameworks and CI/CD',
    ],
    description: `Develop and maintain web interfaces for Airbnb’s platform. 
    Implement UI components, optimize performance, and ensure high-quality user experience. 
    Collaborate with backend engineers and designers to deliver seamless applications.`,
    isApplied: false,
    companyAddress: '888 Brannan St, CA',
    companyIndustry: 'Travel',
    companyWebsite: 'https://www.airbnb.com',
    techStack: [
      'React and Next.js for web development',
      'TypeScript for type-safe code',
      'TailwindCSS for styling',
      'Jest and Cypress for testing',
      'Webpack and Vite for bundling and build',
    ],
    prefferedSkills: [
      'UI/UX design awareness',
      'Testing mindset and debugging',
      'Collaboration and communication',
      'Reusable and maintainable code practices',
      'Continuous learning of new frontend technologies',
    ],
    companyEmployees: 2,
    companyFollowers: 4,
    companyDescription: [
      'Airbnb is a global marketplace that connects hosts offering unique homes and experiences with travelers seeking authentic stays in over 190 countries.',
      'The company redefined hospitality by empowering individuals to share their spaces, fostering cultural exchange and personalized travel experiences.',
      'Airbnb emphasizes sustainability, community, and belonging, shaping the future of tourism while enabling travelers to feel at home anywhere in the world.',
    ],
    createdAt: '2025-09-07T16:40:00',
  },
  {
    id: 10,
    companyName: 'Apple',
    companyLogo: 'assets/logos/apple.png',
    expires: '2025-12-20',
    position: 'iOS Engineer',
    startingSalary: 6500,
    workType: workType.ONSITE,
    location: 'Cupertino',
    country: 'USA',
    qualifications: [
      'Bachelor’s degree in Computer Science, Software Engineering, or related field',
      '3+ years of experience developing iOS applications using Swift and Objective-C',
      'Strong understanding of iOS frameworks (UIKit, CoreData, CoreAnimation)',
      'Experience with RESTful APIs and networking',
      'Knowledge of App Store submission process and best practices',
    ],
    description: `As an iOS Engineer at Apple, you will develop innovative mobile applications 
  for iPhone and iPad. You will collaborate closely with designers, product managers, and backend engineers 
  to deliver high-quality, performant, and user-friendly apps. The role involves writing clean, maintainable code, 
  optimizing for performance, and implementing new features based on user feedback.`,
    isApplied: false,
    companyAddress: '1 Apple Park Way, CA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.apple.com',
    techStack: [
      'Swift and Objective-C for iOS development',
      'Xcode IDE for building and debugging',
      'UIKit, CoreData, CoreAnimation for UI and data management',
      'RESTful APIs and JSON for backend communication',
      'Unit testing frameworks like XCTest',
    ],
    prefferedSkills: [
      'Problem-solving and debugging in complex mobile environments',
      'Attention to detail and high-quality code standards',
      'Collaboration and effective communication with team members',
      'Ability to stay up-to-date with latest iOS developments',
      'Understanding of user experience and design principles',
    ],
    companyEmployees: 21094,
    companyFollowers: 2109423,
    companyDescription: [
      'Apple is a global leader in consumer electronics, software, and digital ecosystems, revolutionizing industries through iconic products like the iPhone, Mac, and iPad.',
      'The company is committed to privacy, design excellence, and seamless integration of hardware and services such as iCloud, Apple Music, and the App Store.',
      'Apple’s culture thrives on innovation, sustainability, and empowering users with intuitive technologies that transform the way people live, work, and connect.',
    ],
    createdAt: '2025-09-06T11:55:00',
  },
  {
    id: 11,
    companyName: 'Apple',
    companyLogo: 'assets/logos/apple.png',
    expires: '2025-12-20',
    position: 'iOS Engineer',
    startingSalary: 6500,
    workType: workType.ONSITE,
    location: 'Cupertino',
    country: 'USA',
    qualifications: [
      'Bachelor’s degree in Computer Science, Software Engineering, or related field',
      '3+ years of experience developing iOS applications using Swift and Objective-C',
      'Strong understanding of iOS frameworks (UIKit, CoreData, CoreAnimation)',
      'Experience with RESTful APIs and networking',
      'Knowledge of App Store submission process and best practices',
    ],
    description: `As an iOS Engineer at Apple, you will develop innovative mobile applications 
  for iPhone and iPad. You will collaborate closely with designers, product managers, and backend engineers 
  to deliver high-quality, performant, and user-friendly apps. The role involves writing clean, maintainable code, 
  optimizing for performance, and implementing new features based on user feedback.`,
    isApplied: false,
    companyAddress: '1 Apple Park Way, CA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.apple.com',
    techStack: [
      'Swift and Objective-C for iOS development',
      'Xcode IDE for building and debugging',
      'UIKit, CoreData, CoreAnimation for UI and data management',
      'RESTful APIs and JSON for backend communication',
      'Unit testing frameworks like XCTest',
    ],
    prefferedSkills: [
      'Problem-solving and debugging in complex mobile environments',
      'Attention to detail and high-quality code standards',
      'Collaboration and effective communication with team members',
      'Ability to stay up-to-date with latest iOS developments',
      'Understanding of user experience and design principles',
    ],
    companyEmployees: 21094,
    companyFollowers: 2109423,
    companyDescription: [
      'Apple is a global leader in consumer electronics, software, and digital ecosystems, revolutionizing industries through iconic products like the iPhone, Mac, and iPad.',
      'The company is committed to privacy, design excellence, and seamless integration of hardware and services such as iCloud, Apple Music, and the App Store.',
      'Apple’s culture thrives on innovation, sustainability, and empowering users with intuitive technologies that transform the way people live, work, and connect.',
    ],
    createdAt: '2025-09-06T11:55:00',
  },
];
