import { workType } from './models/job.enum';
import { Job } from './models/job.model';

export const mockJobs: Job[] = [
  {
    id: 1,
    companyName: 'Google',
    companyLogo: 'assets/logos/google.png',
    expires: '2025-12-31',
    position: 'Frontend Developer',
    startingSalary: 5000,
    workType: workType.REMOTE,
    location: 'Mountain View',
    country: 'USA',
    qualifications: ['BSc in CS', '3+ years experience in Angular/React'],
    description: 'Develop and maintain frontend applications with Angular.',
    isApplied: false,
    companyAddress: '1600 Amphitheatre Parkway, CA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.google.com',
  },
  {
    id: 2,
    companyName: 'Apple',
    companyLogo: 'assets/logos/apple.png',
    expires: '2025-11-15',
    position: 'Backend Developer',
    startingSalary: 6000,
    workType: workType.ONSITE,
    location: 'Cupertino',
    country: 'USA',
    qualifications: ['BSc in CS', '3+ years experience in Node.js/Java'],
    description: 'Build and maintain backend APIs and services.',
    isApplied: true,
    companyAddress: '1 Apple Park Way, CA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.apple.com',
  },
  {
    id: 3,
    companyName: 'Amazon',
    companyLogo: 'assets/logos/amazon.png',
    expires: '2025-10-01',
    position: 'Data Scientist',
    startingSalary: 5500,
    workType: workType.HYBRID,
    location: 'Seattle',
    country: 'USA',
    qualifications: ['MSc in Data Science, Python/R, ML experience'],
    description: 'Analyze large datasets and build predictive models.',
    isApplied: false,
    companyAddress: '410 Terry Ave N, WA',
    companyIndustry: 'E-commerce',
    companyWebsite: 'https://www.amazon.com',
  },
  {
    id: 4,
    companyName: 'Netflix',
    companyLogo: 'assets/logos/netflix.png',
    expires: '2025-09-20',
    position: 'UX Designer',
    startingSalary: 4800,
    workType: workType.HYBRID,
    location: 'Los Gatos',
    country: 'USA',
    qualifications: ['Portfolio of UX projects, Figma/Adobe XD'],
    description: 'Design user-friendly interfaces for streaming platform.',
    isApplied: true,
    companyAddress: '100 Winchester Cir, CA',
    companyIndustry: 'Entertainment',
    companyWebsite: 'https://www.netflix.com',
  },
  {
    id: 5,
    companyName: 'Microsoft',
    companyLogo: 'assets/logos/microsoft.png',
    expires: '2025-08-30',
    position: 'Cloud Engineer',
    startingSalary: 6200,
    workType: workType.ONSITE,
    location: 'Redmond',
    country: 'USA',
    qualifications: ['Azure/AWS experience, DevOps knowledge'],
    description: 'Manage and optimize cloud infrastructure.',
    isApplied: false,
    companyAddress: '1 Microsoft Way, WA',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.microsoft.com',
  },
  {
    id: 6,
    companyName: 'Facebook',
    companyLogo: 'assets/logos/facebook.png',
    expires: '2025-11-05',
    position: 'Mobile Developer',
    startingSalary: 5300,
    workType: workType.HYBRID,
    location: 'Menlo Park',
    country: 'USA',
    qualifications: ['iOS/Android, React Native experience'],
    description: 'Develop mobile applications for social media platform.',
    isApplied: false,
    companyAddress: '1 Hacker Way, CA',
    companyIndustry: 'Social Media',
    companyWebsite: 'https://www.facebook.com',
  },
  {
    id: 7,
    companyName: 'Tesla',
    companyLogo: 'assets/logos/tesla.png',
    expires: '2025-12-15',
    position: 'Mechanical Engineer',
    startingSalary: 5000,
    workType: workType.ONSITE,
    location: 'Palo Alto',
    country: 'USA',
    qualifications: ['BSc in Mechanical Engineering, CAD experience'],
    description: 'Work on design and development of electric vehicles.',
    isApplied: true,
    companyAddress: '3500 Deer Creek Rd, CA',
    companyIndustry: 'Automotive',
    companyWebsite: 'https://www.tesla.com',
  },
  {
    id: 8,
    companyName: 'Spotify',
    companyLogo: 'assets/logos/spotify.png',
    expires: '2025-10-30',
    position: 'Product Manager',
    startingSalary: 5800,
    workType: workType.REMOTE,
    location: 'Stockholm',
    country: 'Sweden',
    qualifications: ['Experience in agile product management, analytics skills'],
    description: 'Lead product development and coordinate teams.',
    isApplied: false,
    companyAddress: 'Regeringsgatan 19, Stockholm',
    companyIndustry: 'Music Streaming',
    companyWebsite: 'https://www.spotify.com',
  },
  {
    id: 9,
    companyName: 'Airbnb',
    companyLogo: 'assets/logos/airbnb.png',
    expires: '2025-09-10',
    position: 'Frontend Developer',
    startingSalary: 5100,
    workType: workType.HYBRID,
    location: 'San Francisco',
    country: 'USA',
    qualifications: ['React, Angular, HTML/CSS, 3+ years experience'],
    description: 'Build and maintain web interfaces for Airbnb platform.',
    isApplied: false,
    companyAddress: '888 Brannan St, CA',
    companyIndustry: 'Travel',
    companyWebsite: 'https://www.airbnb.com',
  },
];
