CREATE TYPE genderStudent AS ENUM ('male', 'female');
CREATE TABLE IF NOT EXISTS Student(
	ID SERIAL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL,
	EnrolledDate DATE NOT NULL,
	Gender genderStudent NOT NULL,
	NationalIDNumber INTEGER NOT NULL,
	StudentCardNumber INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Teacher(
	ID SERIAL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL,
	AcademicRank VARCHAR(25) NOT NULL,
	HireDate DATE
);
CREATE TABLE IF NOT EXISTS Course(
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Credit INTEGER NOT NULL,
	AcademicYear DATE NOT NULL,
	Semester INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Grade(
	ID SERIAL PRIMARY KEY,
	StudentID INTEGER REFERENCES Student(id) NOT NULL,
	CourseID INTEGER REFERENCES Course(id) NOT NULL,
	TeacherID INTEGER REFERENCES Teacher(id) NOT NULL,
	Grade BIT NOT NULL,
	Comment VARCHAR(50),
	CreatedDate DATE
);
CREATE TABLE IF NOT EXISTS AchievementType(
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(100) NOT NULL,
	ParticipationRate INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS GradeDetails(
	ID SERIAL PRIMARY KEY,
	GradeID INTEGER REFERENCES Grade(ID) NOT NULL,
	AchievementTypeID INTEGER REFERENCES AchievementType(ID) NOT NULL,
	AchievementPoints INTEGER NOT NULL,
	AchievementMaxPoints INTEGER,
	AchievementDate DATE NOT NULL
);

SELECT * FROM GradeDetails